version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../config/dev/frontend/Dockerfile
    restart: always
    ports:
      - ${FRONT_PORT}:3000
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: ../config/dev/backend/Dockerfile
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: